### ISSUE TITLE
Zephyr - which GCC does it provide?

### ISSUE THREAD

**Issue by AnttiLukats** [micro-FPGA/riscv-contest-2018#1]
The official rules say: "standard RISC-V GCC provided by Zephyr" however from the zephyr installation and online documentation it is not clear what GCC is used, where it is fetched or how it should be configured.

**Comment by atthecodeface** [comment]
Zephyr does not seem to provide a RISC-V GCC; indeed, I am using my own compile, as I do now want to use meta-zephyr-sdk, which installs compilers for *every* architecture that Zephyr supports. Indeed, I don't have 24GB of spare disk space just for Zephyr...

**Comment by AnttiLukats** [comment]
even if you would use the meta-zephyr-sdk
it would not install zephyr 1.13 GCC as required by the rules, it would install NEWER GCC, not the one that was used for 1.13

**Comment by AnttiLukats** [comment]
solved kind of
