### ISSUE TITLE
Unable to install Libero on Ubuntu 16.04

### ISSUE THREAD

**Issue by raulbehl** [micro-FPGA/riscv-contest-2018#13]
Does Libero supports Ubuntu? I am unable to get the installer working on Ubuntu 16.04. My system is running an Intel i3 processor and has about 250 GB of free space. Any ideas would be appreciated!

**Comment by Dolu1990** [comment]
I tried yesterday, was a paine in the ass, i gived up, will probably use the windows install XD

**Comment by AnttiLukats** [comment]
Sorry folks, I have also as ONLY suggestion to use Windows PC for the Libero as of today it is still easier and faster (usually) to install FPGA vendor tools on winPC than on Linux. Same goes for the JTAG drivers, they need usually some tricks in Linux and may not work from VM, but just work out the box on native Windows PC.

**Comment by kprasadvnsi** [comment]
I did install it on Debian 9 and its PITA to get it working. @raulbehl  if you still want to install on ubuntu ? I will happily help.

**Comment by raulbehl** [comment]
@kprasadvnsi I would really appreciate if you could share the steps with me as well.

**Comment by AnttiLukats** [comment]
i could add in the wiki, tools install section.. sorry I myself really cant help with the linux,

**Comment by kprasadvnsi** [comment]
Sorry, I didn't keep track of package i have installed for Libero Soc. It take me 6 days of my spare time to do it. i remember the most difficult parts but not everything. @raulbehl perhaps we can arrange a Teamviewer Session and do installation on your machine and post the steps here ?

**Comment by Martoni** [comment]
I managed to install it on debian too. I followed (and adapted) the official tutorial from [here](https://www.microsemi.com/document-portal/doc_view/132361-how-to-set-up-your-linux-environment-for-libero) .
But I can't manage to download the bitstream, libero can't find the programmer ...

**Comment by raulbehl** [comment]
@Martoni Thank you so much for sharing the official tutorial here. I'll try to follow the steps today.

**Comment by raulbehl** [comment]
<img width="1083" alt="screenshot 2018-10-30 at 7 49 11 am" src="https://user-images.githubusercontent.com/7036260/47691513-619ff980-dc18-11e8-9be8-19eed1d0ae69.png">


No ubuntu here! :(

**Comment by kprasadvnsi** [comment]
@Martoni here is the udev rules file for Flashpro5 
[70-microsemi.rules.zip](https://github.com/micro-FPGA/riscv-contest-2018/files/2527855/70-microsemi.rules.zip)

**Comment by kprasadvnsi** [comment]
@raulbehl there is no complete guide exist for Ubuntu. let us know where you got stuck with some screenshots of error. and we can help this way.

**Comment by raulbehl** [comment]
@kprasadvnsi Last time when I tried installing, I wasn't even able to fire up the installer itself. I am planning to shift to CentOS and try out the installation there.

**Comment by raulbehl** [comment]
<img width="492" alt="screenshot 2018-10-30 at 1 20 44 pm" src="https://user-images.githubusercontent.com/7036260/47703555-a773b680-dc46-11e8-9f7a-1dbf97b7d792.png">

This is what I see. The file size is ~3.2 GB and I had made it executable as well.

**Comment by kprasadvnsi** [comment]
rename it to Libero_SoC_v11.9_Linux.bin and try again

**Comment by raulbehl** [comment]
Same

**Comment by kprasadvnsi** [comment]
check for checksum of this file by sha256sum Libero_SoC_v11.9_Linux.bin 
it should be:
1418c13081d5c9b12bc181217f6a4c107f6fb91d1d679d08edfdd598209df257

**Comment by FrankBuss** [comment]
I would recommend to install Windows 10, unless you are a masochist. I have done this in a Oracle Virtual Box installation. You can get a Windows 10 key from eBay for like EUR 5, worked great for me. Installation effort gets reduced to clicking the setup.exe files and all the licensing tools, drivers etc. work out of the box. Both Libero and Radiant are working with no problems.

It is not a problem of the software vendors alone, Linux has just too many variations, which results in either a lot of work for the software vendors, if it is not part of the OS package system or other package system, like Python pip, or as in this case, a lot of work on the user side, because nearly all commercial users are still using Windows, so it doesn't make sense for the vendors to spend much money for a perfect Linux installation.

**Comment by Martoni** [comment]
@kprasadvnsi Thanks !
That works now, I can program my board.

**Comment by AnttiLukats** [comment]
solved

**Comment by FrankBuss** [comment]
> You may find an issue when using the FlashPro5 on Virtual Box when downloading the programming file. Please export as an STP file or FlashPro Express Project and download via the FlashPro or FlashPro Express software on a physical machine. This goes for both Libero and SoftConsole.

Works on my Oracle Virtual Box, version 5.2.18. Guest system: Windows 10, host system: latest Linux Debian. Well, at least most of the time. Maybe once out of 10 times the application just closes when I hit the "PROGRAM" button. But if it stays open, it programs the board.

**Comment by Martoni** [comment]
I wrote [my story for Debian installation](http://www.fabienm.eu/flf/installing-libero-on-debian-9/) of libero on my blog (FPGA Liberation Front). If that can help.

**Comment by kprasadvnsi** [comment]
thanks for tutorial. you can do environment variable and license server in one go with using  Terminal. The Libero file you run is a sh script. basically you can define all of thing in Libero script that free you from running license every time you need to start Libero Soc. here is my Libero file.
[libero.zip](https://github.com/micro-FPGA/riscv-contest-2018/files/2545876/libero.zip)
