### ISSUE TITLE
In my Libero_SoC_v11.9 install directory on the Windows7, there is no "snpslmd" 

### ISSUE THREAD

**Issue by cookwchen** [micro-FPGA/riscv-contest-2018#20]

**Comment by mballance** [comment]
Here's a link to the Microsemi Licensing guide:
https://www.microsemi.com/document-portal/doc_view/131602-libero-software-installation-and-licensing-guide

There's a download link in this document to a collection of all licensing software

**Comment by AnttiLukats** [comment]
yes, I think most linux users managed somehow the license hell, so closing the issue.
